# PUT http://ab556.teaching.cs.st-andrews.ac.uk:24033/transfer HTTP/1.1
# content-type: application/json

# {
#     "name": "VHS101",
#     "type": "TAPE",
#     "desc": "Recording of Christmas dinner with family."
# }




//what do they mean by "containing the resources from index offset to offset + limit (excluding the resource at offset + limit)."
//does 2+0 exclude index 2? doesn't make sense since index is position 




















# GET http://localhost:23720/media/21

# POST http://localhost:23720/transfer HTTP/1.1
# content-type: application/json

# {
#     "source": "/media/7", 
#     "target": "http://localhost:23720/media"
# }

# GET http://localhost:23720/media?type=dvd&name=trainspotting&desc=british

# validation check for making sure they input /media/number

POST http://localhost:23720/transfer HTTP/1.1
content-type: application/json

{
    "source": "/media/15", 
    "target": "http://ab556.teaching.cs.st-andrews.ac.uk:24033/media"
}

GET http://ab556.teaching.cs.st-andrews.ac.uk:24033/media/20

# GET  http://localhost:23720/media?offset=2

# GET http://localhost:23720/media

# DELETE http://localhost:23720/media/0

//if its greater than count
//negative offset for previous (when limit is greater than offset) means limit is changed to minimum
//if offset - limit < 0, then change offset to 0 and limit to old offset